- name: Install isutools
  shell:
    cmd: /bin/bash -lc "go install github.com/mazrean/isucon-go-tools/v2/cmd/isutools@{{ isutools_version }}"
- name: Find go.mod
  find:
    path: "{{ app.repo_sync.base }}"
    pattern: go.mod
    recurse: yes
  register: go_mod
- name: Run isutools
  shell:
    cmd: /bin/bash -lc "isutools -fix ./ ; go mod edit -go=1.23 && go mod tidy"
    chdir: "{{ item.path | dirname }}"
  failed_when: no
  with_items: "{{ go_mod.files }}"
- name: Clone repository
  git:
    repo: "{{ repository.repo }}"
    dest: "{{ repository.directory }}"
    version: "{{ repository.branch }}"
    force: yes
    accept_hostkey: yes
- name: Copy app directory
  copy:
    remote_src: yes
    src: "{{ app.repo_sync.base }}/{{ item }}"
    dest: "{{ repository.directory }}/{{ repository.app_path }}/{{ item }}"
    force: yes
  with_items: "{{ app.repo_sync.path_list }}"
  register: app_dir_updated
  when: not ansible_check_mode
- name: Remove ignore app files
  file:
    path: "{{ repository.directory }}/{{ repository.app_path }}/{{ item }}"
    state: absent
  with_items: "{{ app.repo_sync.ignore_list }}"
- name: Push repository
  shell:
    cmd: /bin/bash -lc "git add . && git commit --allow-empty -m \"isutools\" && git push origin {{ repository.branch }}"
    chdir: "{{ repository.directory }}"
  when: app_dir_updated.changed
- name: Set service environment variable
  become: true
  lineinfile:
    line: "{{ item.line }}"
    insertafter: ^\[Service\]
    regexp: "{{ item.regexp }}"
    path: "{{ app.service.file }}"
  with_items:
    - line: Environment=ISUTOOLS_ENABLE=true
      regexp: ^Environment=ISUTOOLS_ENABLE=
    - line: Environment=ISUTOOLS_ADDR=:{{ app.metrics.port }}
      regexp: ^Environment=ISUTOOLS_ADDR=
    - line: Environment=ISUTOOLS_HOST_NAME=isu{{ metrics_num }}
      regexp: ^Environment=ISUTOOLS_HOST_NAME=
    - line: LimitNOFILE=infinity
      regexp: ^LimitNOFILE=
